CREATE TABLE "type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "type" IS 'Tabela para cadastro de tipo de item';
CREATE INDEX "type_index_0"
ON "type" ("name");

CREATE TABLE "subtype" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	"type_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "subtype" IS 'Tabela para cadastro de subtipo do item';
CREATE INDEX "subtype_index_0"
ON "subtype" ("type_id");
CREATE INDEX "subtype_index_1"
ON "subtype" ("name");
CREATE INDEX "subtype_index_2"
ON "subtype" ("name", "type_id");

CREATE TABLE "presentation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "presentation" IS 'Tabela para cadastro de representações de item';
CREATE INDEX "presentation_index_0"
ON "presentation" ("name");

CREATE TABLE "dosage" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"format" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "dosage" IS 'Tabela para cadastro de dosagem de item';
CREATE INDEX "dosage_index_0"
ON "dosage" ("format");

CREATE TABLE "role" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "role" IS 'Tabela para cadastro de funções';
CREATE INDEX "role_index_0"
ON "role" ("name");

CREATE TABLE "user" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	"email" VARCHAR(200) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"role_id" INTEGER NOT NULL,
	"user_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(user_status IN ('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "user" IS 'Tabela para cadastro de usuários';
CREATE INDEX "user_index_0"
ON "user" ("name");
CREATE INDEX "user_index_1"
ON "user" ("email");
CREATE INDEX "user_index_2"
ON "user" ("role_id");
CREATE INDEX "user_index_3"
ON "user" ("user_status");

CREATE TABLE "item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"type_id" INTEGER NOT NULL,
	"presentation_id" INTEGER NOT NULL,
	"dosage_id" INTEGER NOT NULL,
	"subtype_id" INTEGER,
	"item_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(item_status IN ('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER NOT NULL,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "item" IS 'Tabela para cadastro de item';
CREATE INDEX "item_index_0"
ON "item" ("name");
CREATE INDEX "item_index_5"
ON "item" ("item_status");
CREATE INDEX "item_index_8"
ON "item" ("name", "type_id", "presentation_id", "dosage_id", "subtype_id", "item_status");

CREATE TABLE "patient" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(150) NOT NULL,
	"document" VARCHAR(14) NOT NULL UNIQUE,
	"patient_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(patient_status IN('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER NOT NULL,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "patient" IS 'Tabela para cadastro de paciente';
CREATE INDEX "patient_index_0"
ON "patient" ("name");
CREATE INDEX "patient_index_1"
ON "patient" ("document");
CREATE INDEX "patient_index_2"
ON "patient" ("patient_status");
CREATE INDEX "patient_index_3"
ON "patient" ("name", "document", "patient_status");

CREATE TABLE "company_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "company_type" IS 'Tabela para cadastro de tipo de empresa';
CREATE INDEX "company_type_index_0"
ON "company_type" ("name");

CREATE TABLE "company" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"cnpj" VARCHAR(18) NOT NULL UNIQUE,
	"company_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(company_status IN('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER NOT NULL,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "company" IS 'Tabela para cadastro de empresa';
CREATE INDEX "company_index_0"
ON "company" ("name");
CREATE INDEX "company_index_1"
ON "company" ("cnpj");
CREATE INDEX "company_index_2"
ON "company" ("company_status");
CREATE INDEX "company_index_3"
ON "company" ("name", "cnpj", "company_status");

CREATE TABLE "company_type_rel" (
	"company_id" INTEGER NOT NULL,
	"company_type_id" INTEGER NOT NULL,
	PRIMARY KEY("company_id", "company_type_id")
);

COMMENT ON TABLE "company_type_rel" IS 'Tabela para relação de empresa x tipo';


CREATE TABLE "stock_location" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	"code" VARCHAR(50) NOT NULL UNIQUE,
	"is_central_stock" BOOLEAN DEFAULT FALSE,
	"stock_location_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(stock_location_status IN('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "stock_location" IS 'Tabela para cadastro de local de estoque';
CREATE INDEX "stock_location_index_0"
ON "stock_location" ("name");
CREATE INDEX "stock_location_index_1"
ON "stock_location" ("code");
CREATE INDEX "stock_location_index_2"
ON "stock_location" ("stock_location_status");
CREATE INDEX "stock_location_index_3"
ON "stock_location" ("name", "code", "is_central_stock");

CREATE TABLE "advice" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"acronym" VARCHAR(10) NOT NULL UNIQUE,
	"full_name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "advice" IS 'Tabela para cadastro de conselhos';
CREATE INDEX "advice_index_0"
ON "advice" ("acronym");

CREATE TABLE "prescriptor" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(150) NOT NULL,
	"registration_number" VARCHAR(30) NOT NULL UNIQUE,
	"advice_id" INTEGER NOT NULL,
	"specialty" VARCHAR(150),
	"state" CHAR(2) NOT NULL,
	"prescriptor_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(prescriptor_status IN ('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER NOT NULL,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "prescriptor" IS 'Tabela para cadastro de prescritor';
CREATE INDEX "prescriptor_index_0"
ON "prescriptor" ("name");
CREATE INDEX "prescriptor_index_1"
ON "prescriptor" ("registration_number");
CREATE INDEX "prescriptor_index_2"
ON "prescriptor" ("advice_id");
CREATE INDEX "prescriptor_index_3"
ON "prescriptor" ("prescriptor_status");
CREATE INDEX "prescriptor_index_4"
ON "prescriptor" ("name", "registration_number", "advice_id", "prescriptor_status");

CREATE TABLE "batch" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"item_id" INTEGER NOT NULL,
	"company_id" INTEGER NOT NULL,
	"batch_code" VARCHAR(90) NOT NULL UNIQUE,
	"expiration_date" DATE NOT NULL,
	"batch_status" CHAR(1) NOT NULL DEFAULT 'A' CHECK(batch_status IN ('A', 'I')),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"user_created_id" INTEGER NOT NULL,
	"user_updated_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "batch" IS 'Tabela para cadastro de lote';
CREATE INDEX "batch_index_0"
ON "batch" ("item_id");
CREATE INDEX "batch_index_1"
ON "batch" ("company_id");
CREATE INDEX "batch_index_2"
ON "batch" ("batch_code");
CREATE INDEX "batch_index_3"
ON "batch" ("batch_status");
CREATE INDEX "batch_index_4"
ON "batch" ("expiration_date");
CREATE INDEX "batch_index_5"
ON "batch" ("item_id", "company_id", "batch_code", "expiration_date", "batch_status");

CREATE TABLE "stock_balance" (
	"item_id" INTEGER NOT NULL,
	"batch_id" INTEGER NOT NULL,
	"stock_location_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	PRIMARY KEY("item_id", "batch_id", "stock_location_id")
);

COMMENT ON TABLE "stock_balance" IS 'Tabela de estoque de item';
CREATE INDEX "stock_balance_index_0"
ON "stock_balance" ("item_id");
CREATE INDEX "stock_balance_index_1"
ON "stock_balance" ("batch_id");
CREATE INDEX "stock_balance_index_2"
ON "stock_balance" ("stock_location_id");
CREATE INDEX "stock_balance_index_3"
ON "stock_balance" ("batch_id", "item_id", "stock_location_id");

CREATE TABLE "inventory_entry" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"invoice_number" VARCHAR(70),
	"issue_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"entry_date" TIMESTAMPTZ NOT NULL,
	"company_id" INTEGER NOT NULL,
	"entry_type_id" INTEGER NOT NULL,
	"total_value" DECIMAL(12,2),
	"stock_location_id" INTEGER NOT NULL,
	"user_created_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "inventory_entry" IS 'Tabela para entrada de inventário';
CREATE INDEX "inventory_entry_index_0"
ON "inventory_entry" ("invoice_number");
CREATE INDEX "inventory_entry_index_2"
ON "inventory_entry" ("entry_date");
CREATE INDEX "inventory_entry_index_3"
ON "inventory_entry" ("company_id");
CREATE INDEX "inventory_entry_index_6"
ON "inventory_entry" ("entry_type_id");
CREATE INDEX "inventory_entry_index_4"
ON "inventory_entry" ("stock_location_id");
CREATE INDEX "inventory_entry_index_5"
ON "inventory_entry" ("invoice_number", "entry_date", "company_id", "entry_type_id", "stock_location_id");

CREATE TABLE "inventory_entry_item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"inventory_entry_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"batch_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"unit_price" DECIMAL(12,4),
	PRIMARY KEY("id")
);

COMMENT ON TABLE "inventory_entry_item" IS 'Tabela para relação de entrada de item e inventário';
CREATE INDEX "inventory_entry_item_index_0"
ON "inventory_entry_item" ("item_id");
CREATE INDEX "inventory_entry_item_index_1"
ON "inventory_entry_item" ("batch_id");
CREATE INDEX "inventory_entry_item_index_2"
ON "inventory_entry_item" ("inventory_entry_id", "item_id");

CREATE TABLE "inventory_exit" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"exit_type_id" INTEGER NOT NULL,
	"issue_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"exit_date" TIMESTAMPTZ NOT NULL,
	"notes" TEXT NOT NULL,
	"created_user_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "inventory_exit" IS 'Tabela para saída de inventário de item';
CREATE INDEX "inventory_exit_index_0"
ON "inventory_exit" ("exit_type_id");
CREATE INDEX "inventory_exit_index_1"
ON "inventory_exit" ("exit_date");
CREATE INDEX "inventory_exit_index_2"
ON "inventory_exit" ("exit_type_id", "exit_date");

CREATE TABLE "inventory_exit_item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"inventory_exit_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"batch_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "inventory_exit_item" IS 'Tabela para relação de saída de item e inventário';
CREATE INDEX "inventory_exit_item_index_0"
ON "inventory_exit_item" ("item_id");
CREATE INDEX "inventory_exit_item_index_1"
ON "inventory_exit_item" ("batch_id");
CREATE INDEX "inventory_exit_item_index_2"
ON "inventory_exit_item" ("item_id", "batch_id");

CREATE TABLE "stock_transfer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"origin_id" INTEGER NOT NULL,
	"destination_id" INTEGER NOT NULL,
	"issue_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"transfer_date" TIMESTAMPTZ NOT NULL,
	"user_created_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "stock_transfer" IS 'Tabela para transferência de estoque de itens';
CREATE INDEX "stock_transfer_index_0"
ON "stock_transfer" ("origin_id");
CREATE INDEX "stock_transfer_index_1"
ON "stock_transfer" ("destination_id");
CREATE INDEX "stock_transfer_index_2"
ON "stock_transfer" ("transfer_date");
CREATE INDEX "stock_transfer_index_3"
ON "stock_transfer" ("origin_id", "destination_id", "transfer_date");

CREATE TABLE "stock_transfer_item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"stock_transfer_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"batch_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "stock_transfer_item" IS 'Tabela para relação de item com transferência de estoque';
CREATE INDEX "stock_transfer_item_index_0"
ON "stock_transfer_item" ("item_id");
CREATE INDEX "stock_transfer_item_index_1"
ON "stock_transfer_item" ("batch_id");
CREATE INDEX "stock_transfer_item_index_2"
ON "stock_transfer_item" ("item_id", "batch_id");

CREATE TABLE "transfer_request" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"central_stock_id" INTEGER NOT NULL,
	"destination_id" INTEGER NOT NULL,
	"issue_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"request_date" TIMESTAMPTZ NOT NULL,
	"transfer_reason_id" INTEGER NOT NULL,
	"transfer_status" CHAR(1) NOT NULL DEFAULT 'P' CHECK(transfer_status IN('P', 'S', 'C', 'D')),
	"editable_until" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"created_user_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "transfer_request" IS 'Tabela para solicitar transferências de item (status: pending, separation, confirmed e denied)';
CREATE INDEX "transfer_request_index_0"
ON "transfer_request" ("destination_id");
CREATE INDEX "transfer_request_index_1"
ON "transfer_request" ("request_date");
CREATE INDEX "transfer_request_index_2"
ON "transfer_request" ("transfer_reason_id");
CREATE INDEX "transfer_request_index_3"
ON "transfer_request" ("transfer_status");
CREATE INDEX "transfer_request_index_4"
ON "transfer_request" ("editable_until");
CREATE INDEX "transfer_request_index_5"
ON "transfer_request" ("destination_id", "request_date", "transfer_reason_id", "transfer_status", "editable_until");

CREATE TABLE "transfer_request_item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"transfer_request_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"transfer_status" CHAR(1) NOT NULL DEFAULT 'O' CHECK(transfer_status IN('O', 'S', 'F', 'C')),
	"quantity" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "transfer_request_item" IS 'Tabela de relação de pedido de transferência com item (status: open, separation, finished e canceled)';
CREATE INDEX "transfer_request_item_index_0"
ON "transfer_request_item" ("item_id");
CREATE INDEX "transfer_request_item_index_1"
ON "transfer_request_item" ("transfer_status");
CREATE INDEX "transfer_request_item_index_2"
ON "transfer_request_item" ("item_id", "transfer_status");

CREATE TABLE "item_dispensation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"patient_id" INTEGER NOT NULL,
	"prescriptor_id" INTEGER NOT NULL,
	"dispensation_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"user_created_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "item_dispensation" IS 'Tabela para saída de inventário de item por meio da dispensação';
CREATE INDEX "item_dispensation_index_0"
ON "item_dispensation" ("patient_id");
CREATE INDEX "item_dispensation_index_1"
ON "item_dispensation" ("prescriptor_id");
CREATE INDEX "item_dispensation_index_2"
ON "item_dispensation" ("dispensation_date");
CREATE INDEX "item_dispensation_index_3"
ON "item_dispensation" ("patient_id", "prescriptor_id", "dispensation_date");

CREATE TABLE "item_dispensation_item" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"item_dispensation_id" INTEGER NOT NULL,
	"item_id" INTEGER NOT NULL,
	"batch_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"is_psychotropic" BOOLEAN DEFAULT FALSE,
	"prescription_notification_number" VARCHAR(50),
	PRIMARY KEY("id")
);

COMMENT ON TABLE "item_dispensation_item" IS 'Tabela para relação de saída de item por dispensação e inventário';
CREATE INDEX "item_dispensation_item_index_0"
ON "item_dispensation_item" ("item_id");
CREATE INDEX "item_dispensation_item_index_1"
ON "item_dispensation_item" ("batch_id");
CREATE INDEX "item_dispensation_item_index_2"
ON "item_dispensation_item" ("is_psychotropic");
CREATE INDEX "item_dispensation_item_index_3"
ON "item_dispensation_item" ("item_id", "batch_id", "is_psychotropic");

CREATE TABLE "entry_exit_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(150) NOT NULL,
	"type" CHAR(2) NOT NULL CHECK(type IN('EN', 'EX')),
	PRIMARY KEY("id")
);

COMMENT ON TABLE "entry_exit_type" IS 'Tabela para cadastrar tipos de entrada e saída (type: entry e exit)';
CREATE INDEX "entry_exit_type_index_0"
ON "entry_exit_type" ("type");
CREATE INDEX "entry_exit_type_index_1"
ON "entry_exit_type" ("name");
CREATE INDEX "entry_exit_type_index_2"
ON "entry_exit_type" ("name", "type");

CREATE TABLE "transfer_reason" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(150) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "transfer_reason" IS 'Tabela para cadastro de razões de transferências';
CREATE INDEX "transfer_reason_index_0"
ON "transfer_reason" ("name");
ALTER TABLE "user"
ADD FOREIGN KEY("role_id") REFERENCES "role"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("presentation_id") REFERENCES "presentation"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("type_id") REFERENCES "type"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "subtype"
ADD FOREIGN KEY("type_id") REFERENCES "type"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("subtype_id") REFERENCES "subtype"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("dosage_id") REFERENCES "dosage"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "company"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "company"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "company_type_rel"
ADD FOREIGN KEY("company_id") REFERENCES "company"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "company_type_rel"
ADD FOREIGN KEY("company_type_id") REFERENCES "company_type"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_location"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_location"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "prescriptor"
ADD FOREIGN KEY("advice_id") REFERENCES "advice"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "prescriptor"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "prescriptor"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "batch"
ADD FOREIGN KEY("item_id") REFERENCES "item"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "batch"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "batch"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_balance"
ADD FOREIGN KEY("item_id") REFERENCES "item"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_balance"
ADD FOREIGN KEY("batch_id") REFERENCES "batch"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "stock_balance"
ADD FOREIGN KEY("stock_location_id") REFERENCES "stock_location"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "inventory_entry"
ADD FOREIGN KEY("entry_type_id") REFERENCES "entry_exit_type"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_entry"
ADD FOREIGN KEY("stock_location_id") REFERENCES "stock_location"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_entry"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_entry_item"
ADD FOREIGN KEY("inventory_entry_id") REFERENCES "inventory_entry"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_entry_item"
ADD FOREIGN KEY("item_id") REFERENCES "item"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_entry_item"
ADD FOREIGN KEY("batch_id") REFERENCES "batch"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_exit"
ADD FOREIGN KEY("exit_type_id") REFERENCES "entry_exit_type"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "batch"
ADD FOREIGN KEY("company_id") REFERENCES "company"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item_dispensation"
ADD FOREIGN KEY("patient_id") REFERENCES "patient"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item_dispensation"
ADD FOREIGN KEY("prescriptor_id") REFERENCES "prescriptor"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "item_dispensation"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "patient"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "patient"
ADD FOREIGN KEY("user_updated_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer"
ADD FOREIGN KEY("origin_id") REFERENCES "stock_location"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer"
ADD FOREIGN KEY("destination_id") REFERENCES "stock_location"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer"
ADD FOREIGN KEY("user_created_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer_item"
ADD FOREIGN KEY("stock_transfer_id") REFERENCES "stock_transfer"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer_item"
ADD FOREIGN KEY("item_id") REFERENCES "item"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "stock_transfer_item"
ADD FOREIGN KEY("batch_id") REFERENCES "batch"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request"
ADD FOREIGN KEY("central_stock_id") REFERENCES "stock_location"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request"
ADD FOREIGN KEY("destination_id") REFERENCES "stock_location"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request"
ADD FOREIGN KEY("transfer_reason_id") REFERENCES "transfer_reason"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request"
ADD FOREIGN KEY("created_user_id") REFERENCES "user"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request_item"
ADD FOREIGN KEY("transfer_request_id") REFERENCES "transfer_request"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "transfer_request_item"
ADD FOREIGN KEY("item_id") REFERENCES "item"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "inventory_exit_item"
ADD FOREIGN KEY("inventory_exit_id") REFERENCES "inventory_exit"("id")
ON UPDATE RESTRICT ON DELETE RESTRICT;

INSERT INTO "type" (name)
VALUES
('Medicamento'),
('Fórmulas/Leites'),
('Material Médico');

INSERT INTO "subtype" (name, type_id)
VALUES
('Básico', 1),
('Antimicrobiano', 1),
('Psicotrópico', 1);

INSERT INTO "presentation" (name)
VALUES
('Comprimido/Cápsula'),
('Frasco'),
('Bisnaga'),
('Unidade'),
('Lata'),
('Ampola'),
('Caneta');

INSERT INTO "dosage" (format)
VALUES
('mg'),
('mcg'),
('mg/ml'),
('mg/g'),
('ui/ml'),
('g');

INSERT INTO "role" (name)
VALUES
('ADMIN'),
('FARMACEUTICO'),
('OPERADOR');

INSERT INTO "company_type" (name)
VALUES
('Fornecedor'),
('Fabricante');

INSERT INTO "stock_location" (name, code, is_central_stock)
VALUES
('Estoque Central', 'CAF', TRUE);

INSERT INTO "advice" (acronym, full_name)
VALUES
('CRM', 'Conselho Regional de Medicina'),
('CRO', 'Conselho Regional de Odontologia'),
('COREM', 'Conselho Regional de Técnicos em Radiologia'),
('CRMV', 'Conselho Regional de Medicina Veterinária'),
('CRF', 'Conselho Regional de Farmácia'),
('CRN', 'Conselho Regional de Nutrição');

INSERT INTO "entry_exit_type" (name, type)
VALUES
('Nota Fiscal', 'EN'),
('Doação', 'EN'),
('Ajuste de Estoque', 'EN'),
('Perda', 'EX'),
('Ajuste de Estoque', 'EX'),
('Validade Vencida', 'EX'),
('Recolhimento', 'EX');

INSERT INTO "transfer_reason" (name)
VALUES
('Reposição/Consumo'),
('Perda'),
('Validade Vencidade'),
('Recolhimento');