import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1757004175954 implements MigrationInterface {
    name = ' $npmConfigName1757004175954'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."role" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."role_status_enum" NOT NULL DEFAULT 'A', "name" character varying(50) NOT NULL, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."role"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."role"."name" IS 'Nome da função'`);
        await queryRunner.query(`CREATE INDEX "IDX_06ccdafcccf342078162c12753" ON "pharmasys_teste"."role" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."role" IS 'Tabela para cadastro de funções'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."user" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."user_status_enum" NOT NULL DEFAULT 'A', "user_updated_id" integer, "name" character varying(100) NOT NULL, "email" character varying(200) NOT NULL, "password" character varying(255) NOT NULL, "role_id" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."user"."status" IS 'Status do usuário'; COMMENT ON COLUMN "pharmasys_teste"."user"."name" IS 'Nome do usuário'; COMMENT ON COLUMN "pharmasys_teste"."user"."email" IS 'Email do usuário'; COMMENT ON COLUMN "pharmasys_teste"."user"."password" IS 'Senha do usuário'`);
        await queryRunner.query(`CREATE INDEX "IDX_3d44ccf43b8a0d6b9978affb88" ON "pharmasys_teste"."user" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_065d4d8f3b5adb4a08841eae3c" ON "pharmasys_teste"."user" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb2e442d14add3cefbdf33c456" ON "pharmasys_teste"."user" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_65d94d83bbcb43e809fcd82632" ON "pharmasys_teste"."user" ("name", "email", "role_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."user" IS 'Tabela para cadastro de usuários'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."stock_location" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."stock_location_status_enum" NOT NULL DEFAULT 'A', "name" character varying(100) NOT NULL, "code" character varying(50) NOT NULL, "is_central_stock" boolean NOT NULL DEFAULT false, "user_created_id" integer, "user_updated_id" integer, CONSTRAINT "UQ_eb4dd13579b6026ed0449f7a244" UNIQUE ("code"), CONSTRAINT "PK_adf770067d0df1421f525fa25cc" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."stock_location"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."stock_location"."name" IS 'Nome do local de estoque'; COMMENT ON COLUMN "pharmasys_teste"."stock_location"."code" IS 'Código do local de estoque'; COMMENT ON COLUMN "pharmasys_teste"."stock_location"."is_central_stock" IS 'Verifica se é estoque central'`);
        await queryRunner.query(`CREATE INDEX "IDX_b26b82c1f1aeb232ca67d14f27" ON "pharmasys_teste"."stock_location" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f798c40d30ad971fb049e26c3" ON "pharmasys_teste"."stock_location" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e8b8a4b61649c6fa421258fae" ON "pharmasys_teste"."stock_location" ("name", "code") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_location" IS 'Tabela para cadastro de locais de estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."transfer_reason" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, CONSTRAINT "UQ_48bc87a7fca01ee21ce272f71aa" UNIQUE ("name"), CONSTRAINT "PK_ddc7acab5c82b80c08bcf561fef" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."transfer_reason"."name" IS 'Nome das razões de transferência'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."transfer_request" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."transfer_request_status_enum" NOT NULL DEFAULT 'A', "request_date" TIMESTAMP WITH TIME ZONE NOT NULL, "transfer_status" "pharmasys_teste"."transfer_request_transfer_status_enum" NOT NULL DEFAULT 'P', "user_created_id" integer, "user_updated_id" integer, "central_stock_id" integer, "destination_id" integer, "transfer_reason_id" integer, CONSTRAINT "PK_de9b8501ed3bf28cd7dbdcb1d60" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."transfer_request"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."transfer_request"."request_date" IS 'Data do pedido de transferência selecionada pelo usuário'; COMMENT ON COLUMN "pharmasys_teste"."transfer_request"."transfer_status" IS 'Status do pedido de transferência (P-Pendente, S-Separação, C-Concluído, N-Negado)'`);
        await queryRunner.query(`CREATE INDEX "IDX_5b9230be5fa5550b010139fdfe" ON "pharmasys_teste"."transfer_request" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_aefff69f5ce3f1bffb10b876df" ON "pharmasys_teste"."transfer_request" ("central_stock_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bd0657af041ff090b06b61a9a" ON "pharmasys_teste"."transfer_request" ("destination_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e534b6a02089dfec6c54991861" ON "pharmasys_teste"."transfer_request" ("request_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_602bfc244af387a99933800152" ON "pharmasys_teste"."transfer_request" ("transfer_reason_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9bcfa9298263b7da739fdbc77" ON "pharmasys_teste"."transfer_request" ("transfer_status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."transfer_request" IS 'Tabela para cadastro de pedidos de transferência de estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."type" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."type_status_enum" NOT NULL DEFAULT 'A', "name" character varying(100) NOT NULL, CONSTRAINT "UQ_e23bfe7255ada131861292923fe" UNIQUE ("name"), CONSTRAINT "PK_40410d6bf0bedb43f9cadae6fef" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."type"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."type"."name" IS 'Nome do tipo'`);
        await queryRunner.query(`CREATE INDEX "IDX_b2eb5e7d7e223661e53cffef25" ON "pharmasys_teste"."type" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."type" IS 'Tabela para cadastro de tipos de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."presentation" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."presentation_status_enum" NOT NULL DEFAULT 'A', "name" character varying(100) NOT NULL, CONSTRAINT "UQ_7c6d5273ad27dffb942581c7128" UNIQUE ("name"), CONSTRAINT "PK_b3d0364e16cd51d8196a13c528d" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."presentation"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."presentation"."name" IS 'Nome da apresentação'`);
        await queryRunner.query(`CREATE INDEX "IDX_743f058191efdd962457b403c6" ON "pharmasys_teste"."presentation" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."presentation" IS 'Tabela para cadastro de apresentações de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."dosage" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."dosage_status_enum" NOT NULL DEFAULT 'A', "format" character varying(100) NOT NULL, CONSTRAINT "UQ_f210301067d44ba3e7359b5fcba" UNIQUE ("format"), CONSTRAINT "PK_709f3d2911c3d93c12ff020f041" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."dosage"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."dosage"."format" IS 'Formato da dosagem'`);
        await queryRunner.query(`CREATE INDEX "IDX_9f7062ed6b375b22bb3b5e192d" ON "pharmasys_teste"."dosage" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."dosage" IS 'Tabela para cadastro de dosagens de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."subtype" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."subtype_status_enum" NOT NULL DEFAULT 'A', "name" character varying(100) NOT NULL, "type_id" integer, CONSTRAINT "UQ_ad1ad2a6560395aa79d3860119f" UNIQUE ("name"), CONSTRAINT "PK_3c85c72273d84fb92c1fb591963" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."subtype"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."subtype"."name" IS 'Nome do subtipo'`);
        await queryRunner.query(`CREATE INDEX "IDX_3ceb2dd31f49db5876bd340502" ON "pharmasys_teste"."subtype" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."subtype" IS 'Tabela para cadastro de subtipos de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."item_status_enum" NOT NULL DEFAULT 'A', "name" character varying(255) NOT NULL, "user_created_id" integer, "user_updated_id" integer, "type_id" integer, "presentation_id" integer, "dosage_id" integer, "subtype_id" integer, CONSTRAINT "PK_d3c0c71f23e7adcf952a1d13423" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."item"."name" IS 'Nome do item'`);
        await queryRunner.query(`CREATE INDEX "IDX_5d4159d4cf65e41ba84e70fc11" ON "pharmasys_teste"."item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6ae12601fed4e2ee5019544dd" ON "pharmasys_teste"."item" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_64cde7db02a99c28d4b67efb36" ON "pharmasys_teste"."item" ("type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_787ca5aac47f18b87793adef2b" ON "pharmasys_teste"."item" ("presentation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_20edfca72efffb4351690ac3a8" ON "pharmasys_teste"."item" ("dosage_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_033336eb9ed3ac1d5abe9cf350" ON "pharmasys_teste"."item" ("subtype_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2324a27419ed08ee277acc6e5" ON "pharmasys_teste"."item" ("name", "type_id", "presentation_id", "dosage_id", "subtype_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item" IS 'Tabela para o cadastro de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."transfer_request_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."transfer_request_item_status_enum" NOT NULL DEFAULT 'A', "transfer_status" "pharmasys_teste"."transfer_request_item_transfer_status_enum" NOT NULL DEFAULT 'O', "quantity" integer NOT NULL, "transfer_request_id" integer, "item_id" integer, CONSTRAINT "PK_fbcdddf87a0136f887b0849dc69" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."transfer_request_item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."transfer_request_item"."transfer_status" IS 'Status do  item do pedido de transferência (A-Aberto, S-Separação, F-Finalizado, C-Cancelado)'; COMMENT ON COLUMN "pharmasys_teste"."transfer_request_item"."quantity" IS 'Quantidade de cada item'`);
        await queryRunner.query(`CREATE INDEX "IDX_ef274215194b03b985a1037bdf" ON "pharmasys_teste"."transfer_request_item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3ce2eb9eaf59d1af7f5142d8f" ON "pharmasys_teste"."transfer_request_item" ("transfer_request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a05b84bdf411cf3be1a2e69ada" ON "pharmasys_teste"."transfer_request_item" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_484a3a973aa2ac31413a592e1f" ON "pharmasys_teste"."transfer_request_item" ("transfer_status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."transfer_request_item" IS 'Tabela para cadastro de dados do item no pedido de trasnferência de estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."stock_transfer" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."stock_transfer_status_enum" NOT NULL DEFAULT 'A', "transfer_date" TIMESTAMP WITH TIME ZONE NOT NULL, "user_created_id" integer, "user_updated_id" integer, "origin_id" integer, "destination_id" integer, CONSTRAINT "PK_b6165ea3cc5b8062e7eaa1bd44d" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."stock_transfer"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."stock_transfer"."transfer_date" IS 'Data de transferência selecionada pelo usuário'`);
        await queryRunner.query(`CREATE INDEX "IDX_70f17fc214ab5e82cc2eb9245a" ON "pharmasys_teste"."stock_transfer" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_438547aad8702d794e26f1fcea" ON "pharmasys_teste"."stock_transfer" ("origin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7ace1d0ca1821e2f14976edc5" ON "pharmasys_teste"."stock_transfer" ("destination_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_transfer" IS 'Tabela para cadastro de dados de transferência de item do estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."company_type" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."company_type_status_enum" NOT NULL DEFAULT 'A', "name" character varying(100) NOT NULL, CONSTRAINT "UQ_988dc8e37377a72ac44349e35fd" UNIQUE ("name"), CONSTRAINT "PK_b21e9ab8361b2fcc85e6c4f4fa7" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."company_type"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."company_type"."name" IS 'Nome dos tipos de empresa'`);
        await queryRunner.query(`CREATE INDEX "IDX_a9fc849ec4f36385f6d61ddc17" ON "pharmasys_teste"."company_type" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."company_type" IS 'Tabela para cadastro dos tipos de empresa'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."company" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."company_status_enum" NOT NULL DEFAULT 'A', "name" character varying(255) NOT NULL, "cnpj" character varying(18) NOT NULL, "user_created_id" integer, "user_updated_id" integer, CONSTRAINT "UQ_b55d9c6e6adfa3c6de735c5a2eb" UNIQUE ("cnpj"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."company"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."company"."name" IS 'Nome da empresa'; COMMENT ON COLUMN "pharmasys_teste"."company"."cnpj" IS 'CNPJ da empresa'`);
        await queryRunner.query(`CREATE INDEX "IDX_b7a5d746408a6b4beff6af4b93" ON "pharmasys_teste"."company" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a76c5cd486f7779bd9c319afd2" ON "pharmasys_teste"."company" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6681aa20115a9d35994b4c6841" ON "pharmasys_teste"."company" ("name", "cnpj") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."company" IS 'Tabela para cadastro de empresa'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."batch" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."batch_status_enum" NOT NULL DEFAULT 'A', "batch_code" character varying(90) NOT NULL, "expiration_date" date NOT NULL, "user_created_id" integer, "user_updated_id" integer, "item_id" integer, "company_id" integer, CONSTRAINT "UQ_92e8e8867845483820a82e3724d" UNIQUE ("batch_code"), CONSTRAINT "PK_57da3b830b57bec1fd329dcaf43" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."batch"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."batch"."batch_code" IS 'Código do lote'; COMMENT ON COLUMN "pharmasys_teste"."batch"."expiration_date" IS 'Data de expiração'`);
        await queryRunner.query(`CREATE INDEX "IDX_cfea8cb6e387bc8738a456865b" ON "pharmasys_teste"."batch" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4be0d33148594e732642334336" ON "pharmasys_teste"."batch" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af935805ad2c82d42c9c160fb2" ON "pharmasys_teste"."batch" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92e8e8867845483820a82e3724" ON "pharmasys_teste"."batch" ("batch_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fbb92aef269bdb6a6c84720fa" ON "pharmasys_teste"."batch" ("item_id", "company_id", "batch_code") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."batch" IS 'Tabela para cadastro de lotes'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."stock_transfer_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."stock_transfer_item_status_enum" NOT NULL DEFAULT 'A', "quantity" integer NOT NULL, "stock_transfer_id" integer, "item_id" integer, "batch_id" integer, CONSTRAINT "PK_eb4365c2176c09f6dd8e61b27da" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."stock_transfer_item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."stock_transfer_item"."quantity" IS 'Quantidade de cada item'`);
        await queryRunner.query(`CREATE INDEX "IDX_c940735db6215d92f782b5c239" ON "pharmasys_teste"."stock_transfer_item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_756b4af55c5ce54ffb8794c7ab" ON "pharmasys_teste"."stock_transfer_item" ("stock_transfer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fff9ebd9bd2b4d474444cd4980" ON "pharmasys_teste"."stock_transfer_item" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8ac3ae1731c1d49a6921a229d" ON "pharmasys_teste"."stock_transfer_item" ("batch_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_transfer_item" IS 'Tabela para cadastro de dados do item na trasnferência de estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."stock_balance" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."stock_balance_status_enum" NOT NULL DEFAULT 'A', "quantity" integer NOT NULL, "item_id" integer, "batch_id" integer, "stock_location_id" integer, CONSTRAINT "PK_0296c3ed44274fe05333f9609d9" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."stock_balance"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."stock_balance"."quantity" IS 'Quantidade no estoque'`);
        await queryRunner.query(`CREATE INDEX "IDX_0bc5570bc31c816e172e7ee9ad" ON "pharmasys_teste"."stock_balance" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a50119e7fff048aff1efe081ae" ON "pharmasys_teste"."stock_balance" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b9cc86d2e0c604213904f2c30" ON "pharmasys_teste"."stock_balance" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d5f854dd83f415db791512d68" ON "pharmasys_teste"."stock_balance" ("stock_location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_84a5347a12191ddb31eb094665" ON "pharmasys_teste"."stock_balance" ("item_id", "batch_id", "stock_location_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_balance" IS 'Tabela para consulta de estoque'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."advice" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."advice_status_enum" NOT NULL DEFAULT 'A', "acronym" character varying(10) NOT NULL, "full_name" character varying(100) NOT NULL, CONSTRAINT "UQ_8f2a2df5794ca47873bc2506919" UNIQUE ("acronym"), CONSTRAINT "PK_e20d6c014c3233fb2d811c441c3" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."advice"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."advice"."acronym" IS 'Código do conselho'; COMMENT ON COLUMN "pharmasys_teste"."advice"."full_name" IS 'Descrição do conselho'`);
        await queryRunner.query(`CREATE INDEX "IDX_4c9ea2244761f90501a3a46884" ON "pharmasys_teste"."advice" ("status") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."advice" IS 'Tabela para o cadastro dos conselhos profissionais'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."prescriptor" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."prescriptor_status_enum" NOT NULL DEFAULT 'A', "name" character varying(150) NOT NULL, "registration_number" character varying(30) NOT NULL, "specialty" character varying(150), "state" character(2) NOT NULL, "user_created_id" integer, "user_updated_id" integer, "advice_id" integer, CONSTRAINT "UQ_00149dafd65606b748d5bd30674" UNIQUE ("registration_number"), CONSTRAINT "PK_410772504ec7a1ea828e3f09e21" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."prescriptor"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."prescriptor"."name" IS 'Nome do prescritor'; COMMENT ON COLUMN "pharmasys_teste"."prescriptor"."registration_number" IS 'Número de registro do prescritor no conselho profissional'; COMMENT ON COLUMN "pharmasys_teste"."prescriptor"."specialty" IS 'Especialidade do prescritor'; COMMENT ON COLUMN "pharmasys_teste"."prescriptor"."state" IS 'UF do conselho profissional'`);
        await queryRunner.query(`CREATE INDEX "IDX_8f28db9d048a44177d09e814fe" ON "pharmasys_teste"."prescriptor" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d3944bbe4ff9ec516ac4449fc" ON "pharmasys_teste"."prescriptor" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_00149dafd65606b748d5bd3067" ON "pharmasys_teste"."prescriptor" ("registration_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_55a97082454141e5a786963137" ON "pharmasys_teste"."prescriptor" ("advice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce705d727528348ea7bc0dbc75" ON "pharmasys_teste"."prescriptor" ("name", "registration_number", "advice_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."prescriptor" IS 'Tabela para cadastro de prescritores'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."patient" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."patient_status_enum" NOT NULL DEFAULT 'A', "name" character varying(150) NOT NULL, "document" character varying(14) NOT NULL, "user_created_id" integer, "user_updated_id" integer, CONSTRAINT "UQ_56a59567f38ccf4d8209c8e1fc7" UNIQUE ("document"), CONSTRAINT "PK_8dfa510bb29ad31ab2139fbfb99" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."patient"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."patient"."name" IS 'Nome do paciente'; COMMENT ON COLUMN "pharmasys_teste"."patient"."document" IS 'Documento do paciente'`);
        await queryRunner.query(`CREATE INDEX "IDX_93dba9ca93e029fd2e2f103540" ON "pharmasys_teste"."patient" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_054a6cba30d6f51a1cb1e96f38" ON "pharmasys_teste"."patient" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb85fe652952fcdaa00f6078ab" ON "pharmasys_teste"."patient" ("name", "document") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."patient" IS 'Tabela para cadastro de pacientes'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."item_dispensation" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."item_dispensation_status_enum" NOT NULL DEFAULT 'A', "dispensation_date" TIMESTAMP WITH TIME ZONE NOT NULL, "user_created_id" integer, "user_updated_id" integer, "patient_id" integer, "prescriptor_id" integer, CONSTRAINT "PK_4cfe6ce4f87f57b675bf0a1a881" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."item_dispensation"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."item_dispensation"."dispensation_date" IS 'Data da dispensação selecionada pelo usuário'`);
        await queryRunner.query(`CREATE INDEX "IDX_f6051247f677ea801874015d1d" ON "pharmasys_teste"."item_dispensation" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_985c661482eefd9564ed0fe405" ON "pharmasys_teste"."item_dispensation" ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fa4fd2fbe9e8b3f9e2fcc2e33" ON "pharmasys_teste"."item_dispensation" ("prescriptor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e12385d0069718038f7b47689" ON "pharmasys_teste"."item_dispensation" ("dispensation_date") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item_dispensation" IS 'Tabela para cadastro dispensação de itens'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."item_dispensation_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."item_dispensation_item_status_enum" NOT NULL DEFAULT 'A', "quantity" integer NOT NULL, "is_psychotropic" boolean NOT NULL DEFAULT false, "prescription_notification_number" character varying(50), "item_dispensation_id" integer, "item_id" integer, "batch_id" integer, CONSTRAINT "PK_bf8d9f7a025351dc1422e390b58" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."item_dispensation_item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."item_dispensation_item"."quantity" IS 'Quantidade de cada item'; COMMENT ON COLUMN "pharmasys_teste"."item_dispensation_item"."is_psychotropic" IS 'Verifica se é psicotrópico ou não'; COMMENT ON COLUMN "pharmasys_teste"."item_dispensation_item"."prescription_notification_number" IS 'Número da notificação da prescrição (é necessário somente se é psicotrópico)'`);
        await queryRunner.query(`CREATE INDEX "IDX_8c047643abfe8191c5f38517d8" ON "pharmasys_teste"."item_dispensation_item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f5ed6ea366d861b5d05288aac" ON "pharmasys_teste"."item_dispensation_item" ("item_dispensation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0c736b62fed7371ee611f62d6" ON "pharmasys_teste"."item_dispensation_item" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea173d7c0ef85673ea282514e5" ON "pharmasys_teste"."item_dispensation_item" ("batch_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item_dispensation_item" IS 'Tabela para cadastro de dados do item na dispensação'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."exit_item_type" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, CONSTRAINT "UQ_7748f585a6acd2ca7fc7b41821f" UNIQUE ("name"), CONSTRAINT "PK_3108b609c8db00e981b52d6e62a" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."exit_item_type"."name" IS 'Nome dos tipos'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."inventory_exit" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."inventory_exit_status_enum" NOT NULL DEFAULT 'A', "exit_date" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" text NOT NULL, "user_created_id" integer, "user_updated_id" integer, "exit_type_id" integer, CONSTRAINT "PK_b58bfbf5288bf9ed126d8bf807f" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."inventory_exit"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."inventory_exit"."exit_date" IS 'Data de saída informada pelo usuário'; COMMENT ON COLUMN "pharmasys_teste"."inventory_exit"."notes" IS 'Anotações da saída'`);
        await queryRunner.query(`CREATE INDEX "IDX_cf9bb54e20d5b03ce3241016e6" ON "pharmasys_teste"."inventory_exit" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3be00620b50d43dfa8a21fe95" ON "pharmasys_teste"."inventory_exit" ("exit_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bed2ae7c663275515ea7fb7ff" ON "pharmasys_teste"."inventory_exit" ("exit_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fb27a412c76f44fc3a1a5b106" ON "pharmasys_teste"."inventory_exit" ("exit_date", "exit_type_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_exit" IS 'Tabela para cadastro de dados de saída de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."inventory-entry-item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."inventory-entry-item_status_enum" NOT NULL DEFAULT 'A', "quantity" integer NOT NULL, "inventory_exit_id" integer, "item_id" integer, "batch_id" integer, CONSTRAINT "PK_3dbe59931db2eb8a8c39c9d3dca" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."inventory-entry-item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."inventory-entry-item"."quantity" IS 'Quantidade de cada item'`);
        await queryRunner.query(`CREATE INDEX "IDX_abcf39b7c170ec0803a3327edc" ON "pharmasys_teste"."inventory-entry-item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c22f21ce9d953b1f13c2b37e8a" ON "pharmasys_teste"."inventory-entry-item" ("inventory_exit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60bcf2df37d476ac8ba7a96b13" ON "pharmasys_teste"."inventory-entry-item" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc07d411f9eb62b24862cbcfd3" ON "pharmasys_teste"."inventory-entry-item" ("batch_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory-entry-item" IS 'Tabela para cadastro de dados do item na saída'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."entry_item_type" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, CONSTRAINT "UQ_5de3c7fb8b3461a1f13735268ab" UNIQUE ("name"), CONSTRAINT "PK_0dd762d2b87bc363768afc1474b" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."entry_item_type"."name" IS 'Nome dos tipos'`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."entry_item_type" IS 'Tabela para cadastro dos tipos de entrada de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."inventory_entry" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."inventory_entry_status_enum" NOT NULL DEFAULT 'A', "invoice_number" character varying(70), "entry_date" TIMESTAMP WITH TIME ZONE NOT NULL, "total_value" numeric(12,2), "user_created_id" integer, "user_updated_id" integer, "company_id" integer, "entry_type_id" integer, "stock_location_id" integer, CONSTRAINT "PK_6194458c6b3641b5a2d0388b8b7" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."inventory_entry"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."inventory_entry"."invoice_number" IS 'Número da nota fiscal'; COMMENT ON COLUMN "pharmasys_teste"."inventory_entry"."entry_date" IS 'Data de entrada informada pelo usuário'; COMMENT ON COLUMN "pharmasys_teste"."inventory_entry"."total_value" IS 'Valor total se é nota fiscal'`);
        await queryRunner.query(`CREATE INDEX "IDX_e1b81abcf3dca96e5a23a78562" ON "pharmasys_teste"."inventory_entry" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2858582d1072fd7da5547d30db" ON "pharmasys_teste"."inventory_entry" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce08cc8f87e3f3d2b71dcd4933" ON "pharmasys_teste"."inventory_entry" ("entry_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed908c80c627840723b9e3f2e6" ON "pharmasys_teste"."inventory_entry" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7926e4148bba345388fb78cd65" ON "pharmasys_teste"."inventory_entry" ("entry_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_427cb6067b91d7eb5c5792e3b2" ON "pharmasys_teste"."inventory_entry" ("stock_location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d63500d5cb49df1d10eff280a9" ON "pharmasys_teste"."inventory_entry" ("invoice_number", "entry_date") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_entry" IS 'Tabela para cadastro de dados de entrada de item'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."inventory_entry_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "status" "pharmasys_teste"."inventory_entry_item_status_enum" NOT NULL DEFAULT 'A', "quantity" integer NOT NULL, "unit_price" numeric(12,2) NOT NULL, "inventory_entry_id" integer, "item_id" integer, "batch_id" integer, CONSTRAINT "PK_319c8c006922118de3fd3b5cc46" PRIMARY KEY ("id")); COMMENT ON COLUMN "pharmasys_teste"."inventory_entry_item"."status" IS 'Status da entidade (A-Ativo, I-Inativo)'; COMMENT ON COLUMN "pharmasys_teste"."inventory_entry_item"."quantity" IS 'Quantidade de cada item'; COMMENT ON COLUMN "pharmasys_teste"."inventory_entry_item"."unit_price" IS 'Valor de cada item'`);
        await queryRunner.query(`CREATE INDEX "IDX_4ad1b6e872aedaf2cdd684897a" ON "pharmasys_teste"."inventory_entry_item" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a54cdf462d7bf68731f78f672" ON "pharmasys_teste"."inventory_entry_item" ("inventory_entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bad392c4a72d8d36a0ba91818" ON "pharmasys_teste"."inventory_entry_item" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3382e3fc2159ca5be813f64253" ON "pharmasys_teste"."inventory_entry_item" ("batch_id") `);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_entry_item" IS 'Tabela para cadastro de dados do item na entrada'`);
        await queryRunner.query(`CREATE TABLE "pharmasys_teste"."company_type_rel" ("company_id" integer NOT NULL, "company_type_id" integer NOT NULL, CONSTRAINT "PK_152f6c103ee64a472a18a3d627c" PRIMARY KEY ("company_id", "company_type_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f8e9fa7aafdcfbe4adaf4c3af" ON "pharmasys_teste"."company_type_rel" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fea078e5c7c24aa9be1bd7a1f8" ON "pharmasys_teste"."company_type_rel" ("company_type_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "pharmasys_teste"."role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_location" ADD CONSTRAINT "FK_8c7b7c29039c4989f01d7a68001" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_location" ADD CONSTRAINT "FK_b871fdee2b544a3c62ebc1f1be5" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" ADD CONSTRAINT "FK_0c54cc2943d0a7aba8b7540d9e1" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" ADD CONSTRAINT "FK_e2e4bde5ee424669d0cdc1f4219" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" ADD CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe" FOREIGN KEY ("central_stock_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" ADD CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6" FOREIGN KEY ("destination_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" ADD CONSTRAINT "FK_602bfc244af387a99933800152a" FOREIGN KEY ("transfer_reason_id") REFERENCES "pharmasys_teste"."transfer_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."subtype" ADD CONSTRAINT "FK_79896ca02b2da92747610af3c09" FOREIGN KEY ("type_id") REFERENCES "pharmasys_teste"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_50fd2b884d4d505736c27761b49" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_4ed225701049d6bc168d6c104c7" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_64cde7db02a99c28d4b67efb367" FOREIGN KEY ("type_id") REFERENCES "pharmasys_teste"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_787ca5aac47f18b87793adef2b6" FOREIGN KEY ("presentation_id") REFERENCES "pharmasys_teste"."presentation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_20edfca72efffb4351690ac3a8c" FOREIGN KEY ("dosage_id") REFERENCES "pharmasys_teste"."dosage"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" ADD CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507" FOREIGN KEY ("subtype_id") REFERENCES "pharmasys_teste"."subtype"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request_item" ADD CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9" FOREIGN KEY ("transfer_request_id") REFERENCES "pharmasys_teste"."transfer_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request_item" ADD CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" ADD CONSTRAINT "FK_7253746cd5b79181d8f740dbb9c" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" ADD CONSTRAINT "FK_0460f86b13b0d98b11a278c36c9" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" ADD CONSTRAINT "FK_438547aad8702d794e26f1fcea4" FOREIGN KEY ("origin_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" ADD CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a" FOREIGN KEY ("destination_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company" ADD CONSTRAINT "FK_4a100b1bcee44e788e41532c134" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company" ADD CONSTRAINT "FK_60b056105857dee7eb2330ff8c9" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" ADD CONSTRAINT "FK_39e442c989cb7eecdbe0cb48b33" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" ADD CONSTRAINT "FK_07565805e19f9fc90f3824e2e26" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" ADD CONSTRAINT "FK_4be0d33148594e7326423343360" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" ADD CONSTRAINT "FK_af935805ad2c82d42c9c160fb29" FOREIGN KEY ("company_id") REFERENCES "pharmasys_teste"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" ADD CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6" FOREIGN KEY ("stock_transfer_id") REFERENCES "pharmasys_teste"."stock_transfer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" ADD CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" ADD CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd" FOREIGN KEY ("batch_id") REFERENCES "pharmasys_teste"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" ADD CONSTRAINT "FK_a50119e7fff048aff1efe081aef" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" ADD CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309" FOREIGN KEY ("batch_id") REFERENCES "pharmasys_teste"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" ADD CONSTRAINT "FK_4d5f854dd83f415db791512d68a" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" ADD CONSTRAINT "FK_848df84b4888c0a364bbc6e1031" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" ADD CONSTRAINT "FK_98c723a430a0587554a25cce0a1" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" ADD CONSTRAINT "FK_55a97082454141e5a7869631375" FOREIGN KEY ("advice_id") REFERENCES "pharmasys_teste"."advice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."patient" ADD CONSTRAINT "FK_c2a66daa04002f737670a0091c9" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."patient" ADD CONSTRAINT "FK_198454fde47aa720ec4cc990d43" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" ADD CONSTRAINT "FK_fa2a37ac2e39c019ccd2c10b295" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" ADD CONSTRAINT "FK_1aee4e1a4ebb77c7afa4c45dc8d" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" ADD CONSTRAINT "FK_985c661482eefd9564ed0fe405c" FOREIGN KEY ("patient_id") REFERENCES "pharmasys_teste"."patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" ADD CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b" FOREIGN KEY ("prescriptor_id") REFERENCES "pharmasys_teste"."prescriptor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" ADD CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb" FOREIGN KEY ("item_dispensation_id") REFERENCES "pharmasys_teste"."item_dispensation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" ADD CONSTRAINT "FK_e0c736b62fed7371ee611f62d68" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" ADD CONSTRAINT "FK_ea173d7c0ef85673ea282514e56" FOREIGN KEY ("batch_id") REFERENCES "pharmasys_teste"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" ADD CONSTRAINT "FK_f5dbf51fc979628d4a372490964" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" ADD CONSTRAINT "FK_aaea6ec1c3ab2db255c223dce94" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" ADD CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9" FOREIGN KEY ("exit_type_id") REFERENCES "pharmasys_teste"."exit_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" ADD CONSTRAINT "FK_c22f21ce9d953b1f13c2b37e8a5" FOREIGN KEY ("inventory_exit_id") REFERENCES "pharmasys_teste"."inventory_exit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" ADD CONSTRAINT "FK_60bcf2df37d476ac8ba7a96b13a" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" ADD CONSTRAINT "FK_fc07d411f9eb62b24862cbcfd3d" FOREIGN KEY ("batch_id") REFERENCES "pharmasys_teste"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" ADD CONSTRAINT "FK_5e334dad6f0fccd15569f4f6820" FOREIGN KEY ("user_created_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" ADD CONSTRAINT "FK_8d196f74d8444326306f7f4c3eb" FOREIGN KEY ("user_updated_id") REFERENCES "pharmasys_teste"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" ADD CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b" FOREIGN KEY ("company_id") REFERENCES "pharmasys_teste"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" ADD CONSTRAINT "FK_7926e4148bba345388fb78cd657" FOREIGN KEY ("entry_type_id") REFERENCES "pharmasys_teste"."entry_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" ADD CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys_teste"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" ADD CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a" FOREIGN KEY ("inventory_entry_id") REFERENCES "pharmasys_teste"."inventory_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" ADD CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f" FOREIGN KEY ("item_id") REFERENCES "pharmasys_teste"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" ADD CONSTRAINT "FK_3382e3fc2159ca5be813f642538" FOREIGN KEY ("batch_id") REFERENCES "pharmasys_teste"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company_type_rel" ADD CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4" FOREIGN KEY ("company_id") REFERENCES "pharmasys_teste"."company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company_type_rel" ADD CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86" FOREIGN KEY ("company_type_id") REFERENCES "pharmasys_teste"."company_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company_type_rel" DROP CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company_type_rel" DROP CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" DROP CONSTRAINT "FK_3382e3fc2159ca5be813f642538"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" DROP CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry_item" DROP CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" DROP CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" DROP CONSTRAINT "FK_7926e4148bba345388fb78cd657"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" DROP CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" DROP CONSTRAINT "FK_8d196f74d8444326306f7f4c3eb"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_entry" DROP CONSTRAINT "FK_5e334dad6f0fccd15569f4f6820"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" DROP CONSTRAINT "FK_fc07d411f9eb62b24862cbcfd3d"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" DROP CONSTRAINT "FK_60bcf2df37d476ac8ba7a96b13a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory-entry-item" DROP CONSTRAINT "FK_c22f21ce9d953b1f13c2b37e8a5"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" DROP CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" DROP CONSTRAINT "FK_aaea6ec1c3ab2db255c223dce94"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."inventory_exit" DROP CONSTRAINT "FK_f5dbf51fc979628d4a372490964"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" DROP CONSTRAINT "FK_ea173d7c0ef85673ea282514e56"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" DROP CONSTRAINT "FK_e0c736b62fed7371ee611f62d68"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation_item" DROP CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" DROP CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" DROP CONSTRAINT "FK_985c661482eefd9564ed0fe405c"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" DROP CONSTRAINT "FK_1aee4e1a4ebb77c7afa4c45dc8d"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item_dispensation" DROP CONSTRAINT "FK_fa2a37ac2e39c019ccd2c10b295"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."patient" DROP CONSTRAINT "FK_198454fde47aa720ec4cc990d43"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."patient" DROP CONSTRAINT "FK_c2a66daa04002f737670a0091c9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" DROP CONSTRAINT "FK_55a97082454141e5a7869631375"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" DROP CONSTRAINT "FK_98c723a430a0587554a25cce0a1"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."prescriptor" DROP CONSTRAINT "FK_848df84b4888c0a364bbc6e1031"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" DROP CONSTRAINT "FK_4d5f854dd83f415db791512d68a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" DROP CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_balance" DROP CONSTRAINT "FK_a50119e7fff048aff1efe081aef"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" DROP CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" DROP CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer_item" DROP CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" DROP CONSTRAINT "FK_af935805ad2c82d42c9c160fb29"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" DROP CONSTRAINT "FK_4be0d33148594e7326423343360"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" DROP CONSTRAINT "FK_07565805e19f9fc90f3824e2e26"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."batch" DROP CONSTRAINT "FK_39e442c989cb7eecdbe0cb48b33"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company" DROP CONSTRAINT "FK_60b056105857dee7eb2330ff8c9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."company" DROP CONSTRAINT "FK_4a100b1bcee44e788e41532c134"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" DROP CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" DROP CONSTRAINT "FK_438547aad8702d794e26f1fcea4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" DROP CONSTRAINT "FK_0460f86b13b0d98b11a278c36c9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_transfer" DROP CONSTRAINT "FK_7253746cd5b79181d8f740dbb9c"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request_item" DROP CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request_item" DROP CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_20edfca72efffb4351690ac3a8c"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_787ca5aac47f18b87793adef2b6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_64cde7db02a99c28d4b67efb367"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_4ed225701049d6bc168d6c104c7"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."item" DROP CONSTRAINT "FK_50fd2b884d4d505736c27761b49"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."subtype" DROP CONSTRAINT "FK_79896ca02b2da92747610af3c09"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" DROP CONSTRAINT "FK_602bfc244af387a99933800152a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" DROP CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" DROP CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" DROP CONSTRAINT "FK_e2e4bde5ee424669d0cdc1f4219"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."transfer_request" DROP CONSTRAINT "FK_0c54cc2943d0a7aba8b7540d9e1"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_location" DROP CONSTRAINT "FK_b871fdee2b544a3c62ebc1f1be5"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."stock_location" DROP CONSTRAINT "FK_8c7b7c29039c4989f01d7a68001"`);
        await queryRunner.query(`ALTER TABLE "pharmasys_teste"."user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_fea078e5c7c24aa9be1bd7a1f8"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_6f8e9fa7aafdcfbe4adaf4c3af"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."company_type_rel"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_entry_item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3382e3fc2159ca5be813f64253"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_4bad392c4a72d8d36a0ba91818"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_8a54cdf462d7bf68731f78f672"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_4ad1b6e872aedaf2cdd684897a"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."inventory_entry_item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_entry" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_d63500d5cb49df1d10eff280a9"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_427cb6067b91d7eb5c5792e3b2"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_7926e4148bba345388fb78cd65"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_ed908c80c627840723b9e3f2e6"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_ce08cc8f87e3f3d2b71dcd4933"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_2858582d1072fd7da5547d30db"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_e1b81abcf3dca96e5a23a78562"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."inventory_entry"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."entry_item_type" IS NULL`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."entry_item_type"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory-entry-item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_fc07d411f9eb62b24862cbcfd3"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_60bcf2df37d476ac8ba7a96b13"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_c22f21ce9d953b1f13c2b37e8a"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_abcf39b7c170ec0803a3327edc"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."inventory-entry-item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."inventory_exit" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_7fb27a412c76f44fc3a1a5b106"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_0bed2ae7c663275515ea7fb7ff"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_e3be00620b50d43dfa8a21fe95"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_cf9bb54e20d5b03ce3241016e6"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."inventory_exit"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."exit_item_type"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item_dispensation_item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_ea173d7c0ef85673ea282514e5"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_e0c736b62fed7371ee611f62d6"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_9f5ed6ea366d861b5d05288aac"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_8c047643abfe8191c5f38517d8"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."item_dispensation_item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item_dispensation" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_7e12385d0069718038f7b47689"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3fa4fd2fbe9e8b3f9e2fcc2e33"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_985c661482eefd9564ed0fe405"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_f6051247f677ea801874015d1d"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."item_dispensation"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."patient" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_bb85fe652952fcdaa00f6078ab"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_054a6cba30d6f51a1cb1e96f38"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_93dba9ca93e029fd2e2f103540"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."patient"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."prescriptor" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_ce705d727528348ea7bc0dbc75"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_55a97082454141e5a786963137"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_00149dafd65606b748d5bd3067"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_8d3944bbe4ff9ec516ac4449fc"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_8f28db9d048a44177d09e814fe"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."prescriptor"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."advice" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_4c9ea2244761f90501a3a46884"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."advice"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_balance" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_84a5347a12191ddb31eb094665"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_4d5f854dd83f415db791512d68"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_7b9cc86d2e0c604213904f2c30"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a50119e7fff048aff1efe081ae"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_0bc5570bc31c816e172e7ee9ad"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."stock_balance"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_transfer_item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_b8ac3ae1731c1d49a6921a229d"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_fff9ebd9bd2b4d474444cd4980"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_756b4af55c5ce54ffb8794c7ab"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_c940735db6215d92f782b5c239"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."stock_transfer_item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."batch" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3fbb92aef269bdb6a6c84720fa"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_92e8e8867845483820a82e3724"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_af935805ad2c82d42c9c160fb2"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_4be0d33148594e732642334336"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_cfea8cb6e387bc8738a456865b"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."batch"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."company" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_6681aa20115a9d35994b4c6841"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a76c5cd486f7779bd9c319afd2"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_b7a5d746408a6b4beff6af4b93"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."company"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."company_type" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a9fc849ec4f36385f6d61ddc17"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."company_type"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_transfer" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_e7ace1d0ca1821e2f14976edc5"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_438547aad8702d794e26f1fcea"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_70f17fc214ab5e82cc2eb9245a"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."stock_transfer"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."transfer_request_item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_484a3a973aa2ac31413a592e1f"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a05b84bdf411cf3be1a2e69ada"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_b3ce2eb9eaf59d1af7f5142d8f"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_ef274215194b03b985a1037bdf"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."transfer_request_item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."item" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a2324a27419ed08ee277acc6e5"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_033336eb9ed3ac1d5abe9cf350"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_20edfca72efffb4351690ac3a8"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_787ca5aac47f18b87793adef2b"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_64cde7db02a99c28d4b67efb36"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_c6ae12601fed4e2ee5019544dd"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_5d4159d4cf65e41ba84e70fc11"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."item"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."subtype" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3ceb2dd31f49db5876bd340502"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."subtype"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."dosage" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_9f7062ed6b375b22bb3b5e192d"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."dosage"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."presentation" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_743f058191efdd962457b403c6"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."presentation"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."type" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_b2eb5e7d7e223661e53cffef25"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."type"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."transfer_request" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_a9bcfa9298263b7da739fdbc77"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_602bfc244af387a99933800152"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_e534b6a02089dfec6c54991861"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_0bd0657af041ff090b06b61a9a"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_aefff69f5ce3f1bffb10b876df"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_5b9230be5fa5550b010139fdfe"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."transfer_request"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."transfer_reason"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."stock_location" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_5e8b8a4b61649c6fa421258fae"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3f798c40d30ad971fb049e26c3"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_b26b82c1f1aeb232ca67d14f27"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."stock_location"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."user" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_65d94d83bbcb43e809fcd82632"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_fb2e442d14add3cefbdf33c456"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_065d4d8f3b5adb4a08841eae3c"`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_3d44ccf43b8a0d6b9978affb88"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."user"`);
        await queryRunner.query(`COMMENT ON TABLE "pharmasys_teste"."role" IS NULL`);
        await queryRunner.query(`DROP INDEX "pharmasys_teste"."IDX_06ccdafcccf342078162c12753"`);
        await queryRunner.query(`DROP TABLE "pharmasys_teste"."role"`);
    }

}
