import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCommentsInBaseEntity1762173580239 implements MigrationInterface {
    name = 'AddCommentsInBaseEntity1762173580239'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_65d94d83bbcb43e809fcd82632"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."user"."role_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_4d5f854dd83f415db791512d68a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" DROP CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" DROP CONSTRAINT "FK_438547aad8702d794e26f1fcea4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_602bfc244af387a99933800152a"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" DROP CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."central_stock_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."destination_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."transfer_reason_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" DROP CONSTRAINT "FK_79896ca02b2da92747610af3c09"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_64cde7db02a99c28d4b67efb367"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_787ca5aac47f18b87793adef2b6"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_20edfca72efffb4351690ac3a8c"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."type_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_a50119e7fff048aff1efe081aef"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" DROP CONSTRAINT "FK_4be0d33148594e7326423343360"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_941263ddd34c1aa7168e1145c88"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" DROP CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_e0c736b62fed7371ee611f62d68"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_a2324a27419ed08ee277acc6e5"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."type_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."presentation_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."dosage_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."subtype_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."transfer_request_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" DROP CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" DROP CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" DROP CONSTRAINT "FK_af935805ad2c82d42c9c160fb29"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_3382e3fc2159ca5be813f642538"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_4f5973e1a34ffaa833f4e32e256"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_ea173d7c0ef85673ea282514e56"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_3fbb92aef269bdb6a6c84720fa"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."company_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."origin_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."destination_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."stock_transfer_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."batch_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_84a5347a12191ddb31eb094665"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."batch_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."stock_location_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" DROP CONSTRAINT "FK_55a97082454141e5a7869631375"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" DROP CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_ce705d727528348ea7bc0dbc75"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."advice_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" DROP CONSTRAINT "FK_985c661482eefd9564ed0fe405c"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."patient_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."prescriptor_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."item_dispensation_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."batch_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" DROP CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_ba8c099d85e98afa1bad268e683"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_7fb27a412c76f44fc3a1a5b106"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."exit_type_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."inventory_exit_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."batch_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_7926e4148bba345388fb78cd657"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."company_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."entry_type_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."stock_location_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."created_at" IS 'Data de criação da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."updated_at" IS 'Data de atualização da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."deleted_at" IS 'Data de exclusão da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."inventory_entry_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."item_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."batch_id" IS 'Identificador único da entidade'`);
        await queryRunner.query(`CREATE INDEX "IDX_65d94d83bbcb43e809fcd82632" ON "pharmasys"."user" ("name", "email", "role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2324a27419ed08ee277acc6e5" ON "pharmasys"."item" ("name", "type_id", "presentation_id", "dosage_id", "subtype_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fbb92aef269bdb6a6c84720fa" ON "pharmasys"."batch" ("item_id", "company_id", "batch_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_84a5347a12191ddb31eb094665" ON "pharmasys"."stock_balance" ("item_id", "batch_id", "stock_location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce705d727528348ea7bc0dbc75" ON "pharmasys"."prescriptor" ("name", "registration_number", "advice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fb27a412c76f44fc3a1a5b106" ON "pharmasys"."inventory_exit" ("exit_date", "exit_type_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "pharmasys"."role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe" FOREIGN KEY ("central_stock_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6" FOREIGN KEY ("destination_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_602bfc244af387a99933800152a" FOREIGN KEY ("transfer_reason_id") REFERENCES "pharmasys"."transfer_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ADD CONSTRAINT "FK_79896ca02b2da92747610af3c09" FOREIGN KEY ("type_id") REFERENCES "pharmasys"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_64cde7db02a99c28d4b67efb367" FOREIGN KEY ("type_id") REFERENCES "pharmasys"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_787ca5aac47f18b87793adef2b6" FOREIGN KEY ("presentation_id") REFERENCES "pharmasys"."presentation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_20edfca72efffb4351690ac3a8c" FOREIGN KEY ("dosage_id") REFERENCES "pharmasys"."dosage"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507" FOREIGN KEY ("subtype_id") REFERENCES "pharmasys"."subtype"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ADD CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9" FOREIGN KEY ("transfer_request_id") REFERENCES "pharmasys"."transfer_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ADD CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ADD CONSTRAINT "FK_4be0d33148594e7326423343360" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ADD CONSTRAINT "FK_af935805ad2c82d42c9c160fb29" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ADD CONSTRAINT "FK_438547aad8702d794e26f1fcea4" FOREIGN KEY ("origin_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ADD CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a" FOREIGN KEY ("destination_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6" FOREIGN KEY ("stock_transfer_id") REFERENCES "pharmasys"."stock_transfer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_a50119e7fff048aff1efe081aef" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_4d5f854dd83f415db791512d68a" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ADD CONSTRAINT "FK_55a97082454141e5a7869631375" FOREIGN KEY ("advice_id") REFERENCES "pharmasys"."advice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ADD CONSTRAINT "FK_985c661482eefd9564ed0fe405c" FOREIGN KEY ("patient_id") REFERENCES "pharmasys"."patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ADD CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b" FOREIGN KEY ("prescriptor_id") REFERENCES "pharmasys"."prescriptor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb" FOREIGN KEY ("item_dispensation_id") REFERENCES "pharmasys"."item_dispensation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_e0c736b62fed7371ee611f62d68" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_ea173d7c0ef85673ea282514e56" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ADD CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9" FOREIGN KEY ("exit_type_id") REFERENCES "pharmasys"."exit_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_ba8c099d85e98afa1bad268e683" FOREIGN KEY ("inventory_exit_id") REFERENCES "pharmasys"."inventory_exit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_941263ddd34c1aa7168e1145c88" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_4f5973e1a34ffaa833f4e32e256" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_7926e4148bba345388fb78cd657" FOREIGN KEY ("entry_type_id") REFERENCES "pharmasys"."entry_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a" FOREIGN KEY ("inventory_entry_id") REFERENCES "pharmasys"."inventory_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_3382e3fc2159ca5be813f642538" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" ADD CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" ADD CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86" FOREIGN KEY ("company_type_id") REFERENCES "pharmasys"."company_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" DROP CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" DROP CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_3382e3fc2159ca5be813f642538"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" DROP CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_7926e4148bba345388fb78cd657"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" DROP CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_4f5973e1a34ffaa833f4e32e256"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_941263ddd34c1aa7168e1145c88"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" DROP CONSTRAINT "FK_ba8c099d85e98afa1bad268e683"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" DROP CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_ea173d7c0ef85673ea282514e56"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_e0c736b62fed7371ee611f62d68"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" DROP CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" DROP CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" DROP CONSTRAINT "FK_985c661482eefd9564ed0fe405c"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" DROP CONSTRAINT "FK_55a97082454141e5a7869631375"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_4d5f854dd83f415db791512d68a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" DROP CONSTRAINT "FK_a50119e7fff048aff1efe081aef"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" DROP CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" DROP CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" DROP CONSTRAINT "FK_438547aad8702d794e26f1fcea4"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" DROP CONSTRAINT "FK_af935805ad2c82d42c9c160fb29"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" DROP CONSTRAINT "FK_4be0d33148594e7326423343360"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" DROP CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" DROP CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_20edfca72efffb4351690ac3a8c"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_787ca5aac47f18b87793adef2b6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" DROP CONSTRAINT "FK_64cde7db02a99c28d4b67efb367"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" DROP CONSTRAINT "FK_79896ca02b2da92747610af3c09"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_602bfc244af387a99933800152a"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" DROP CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_7fb27a412c76f44fc3a1a5b106"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_ce705d727528348ea7bc0dbc75"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_84a5347a12191ddb31eb094665"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_3fbb92aef269bdb6a6c84720fa"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_a2324a27419ed08ee277acc6e5"`);
        await queryRunner.query(`DROP INDEX "pharmasys"."IDX_65d94d83bbcb43e809fcd82632"`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."batch_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."inventory_entry_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry_item"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."stock_location_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."entry_type_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."company_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_entry"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_8a54cdf462d7bf68731f78f672a" FOREIGN KEY ("inventory_entry_id") REFERENCES "pharmasys"."inventory_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."entry_item_type"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_7926e4148bba345388fb78cd657" FOREIGN KEY ("entry_type_id") REFERENCES "pharmasys"."entry_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."batch_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."inventory_exit_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory-exit-item"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."exit_type_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."inventory_exit"."id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_7fb27a412c76f44fc3a1a5b106" ON "pharmasys"."inventory_exit" ("exit_date", "exit_type_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_ba8c099d85e98afa1bad268e683" FOREIGN KEY ("inventory_exit_id") REFERENCES "pharmasys"."inventory_exit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."exit_item_type"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ADD CONSTRAINT "FK_0bed2ae7c663275515ea7fb7ff9" FOREIGN KEY ("exit_type_id") REFERENCES "pharmasys"."exit_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."batch_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."item_dispensation_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation_item"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."prescriptor_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."patient_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item_dispensation"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_9f5ed6ea366d861b5d05288aacb" FOREIGN KEY ("item_dispensation_id") REFERENCES "pharmasys"."item_dispensation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."patient"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ADD CONSTRAINT "FK_985c661482eefd9564ed0fe405c" FOREIGN KEY ("patient_id") REFERENCES "pharmasys"."patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."advice_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."prescriptor"."id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_ce705d727528348ea7bc0dbc75" ON "pharmasys"."prescriptor" ("name", "registration_number", "advice_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ADD CONSTRAINT "FK_3fa4fd2fbe9e8b3f9e2fcc2e33b" FOREIGN KEY ("prescriptor_id") REFERENCES "pharmasys"."prescriptor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."advice"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ADD CONSTRAINT "FK_55a97082454141e5a7869631375" FOREIGN KEY ("advice_id") REFERENCES "pharmasys"."advice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."stock_location_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."batch_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_balance"."id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_84a5347a12191ddb31eb094665" ON "pharmasys"."stock_balance" ("item_id", "batch_id", "stock_location_id") `);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."batch_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."stock_transfer_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer_item"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."destination_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."origin_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_transfer"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_756b4af55c5ce54ffb8794c7ab6" FOREIGN KEY ("stock_transfer_id") REFERENCES "pharmasys"."stock_transfer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."company_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."batch"."id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_3fbb92aef269bdb6a6c84720fa" ON "pharmasys"."batch" ("batch_code", "item_id", "company_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_ea173d7c0ef85673ea282514e56" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_b8ac3ae1731c1d49a6921a229dd" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_4f5973e1a34ffaa833f4e32e256" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_3382e3fc2159ca5be813f642538" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_7b9cc86d2e0c604213904f2c309" FOREIGN KEY ("batch_id") REFERENCES "pharmasys"."batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_ed908c80c627840723b9e3f2e6b" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ADD CONSTRAINT "FK_af935805ad2c82d42c9c160fb29" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" ADD CONSTRAINT "FK_6f8e9fa7aafdcfbe4adaf4c3af4" FOREIGN KEY ("company_id") REFERENCES "pharmasys"."company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."company_type"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type_rel" ADD CONSTRAINT "FK_fea078e5c7c24aa9be1bd7a1f86" FOREIGN KEY ("company_type_id") REFERENCES "pharmasys"."company_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."item_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."transfer_request_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request_item"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."subtype_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."dosage_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."presentation_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."type_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."item"."id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_a2324a27419ed08ee277acc6e5" ON "pharmasys"."item" ("name", "type_id", "presentation_id", "dosage_id", "subtype_id") `);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ADD CONSTRAINT "FK_e0c736b62fed7371ee611f62d68" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ADD CONSTRAINT "FK_a05b84bdf411cf3be1a2e69adac" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ADD CONSTRAINT "FK_fff9ebd9bd2b4d474444cd49802" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ADD CONSTRAINT "FK_941263ddd34c1aa7168e1145c88" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ADD CONSTRAINT "FK_4bad392c4a72d8d36a0ba91818f" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ADD CONSTRAINT "FK_4be0d33148594e7326423343360" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_a50119e7fff048aff1efe081aef" FOREIGN KEY ("item_id") REFERENCES "pharmasys"."item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."type_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."subtype"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_033336eb9ed3ac1d5abe9cf3507" FOREIGN KEY ("subtype_id") REFERENCES "pharmasys"."subtype"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."dosage"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_20edfca72efffb4351690ac3a8c" FOREIGN KEY ("dosage_id") REFERENCES "pharmasys"."dosage"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."presentation"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_787ca5aac47f18b87793adef2b6" FOREIGN KEY ("presentation_id") REFERENCES "pharmasys"."presentation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."type"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ADD CONSTRAINT "FK_64cde7db02a99c28d4b67efb367" FOREIGN KEY ("type_id") REFERENCES "pharmasys"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ADD CONSTRAINT "FK_79896ca02b2da92747610af3c09" FOREIGN KEY ("type_id") REFERENCES "pharmasys"."type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."transfer_reason_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."destination_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."central_stock_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_request"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ADD CONSTRAINT "FK_b3ce2eb9eaf59d1af7f5142d8f9" FOREIGN KEY ("transfer_request_id") REFERENCES "pharmasys"."transfer_request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."transfer_reason"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_602bfc244af387a99933800152a" FOREIGN KEY ("transfer_reason_id") REFERENCES "pharmasys"."transfer_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."stock_location"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_aefff69f5ce3f1bffb10b876dfe" FOREIGN KEY ("central_stock_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ADD CONSTRAINT "FK_0bd0657af041ff090b06b61a9a6" FOREIGN KEY ("destination_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ADD CONSTRAINT "FK_438547aad8702d794e26f1fcea4" FOREIGN KEY ("origin_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ADD CONSTRAINT "FK_e7ace1d0ca1821e2f14976edc5a" FOREIGN KEY ("destination_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ADD CONSTRAINT "FK_427cb6067b91d7eb5c5792e3b28" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ADD CONSTRAINT "FK_4d5f854dd83f415db791512d68a" FOREIGN KEY ("stock_location_id") REFERENCES "pharmasys"."stock_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."user"."role_id" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_65d94d83bbcb43e809fcd82632" ON "pharmasys"."user" ("name", "email", "role_id") `);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."deleted_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."updated_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pharmasys"."role"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "pharmasys"."role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
