import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateStatusEnum1765929229921 implements MigrationInterface {
    name = 'UpdateStatusEnum1765929229921'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "pharmasys"."role_status_enum" RENAME TO "role_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."role_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" TYPE "pharmasys"."role_status_enum" USING "status"::"text"::"pharmasys"."role_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."role_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."user_status_enum" RENAME TO "user_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."user_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" TYPE "pharmasys"."user_status_enum" USING "status"::"text"::"pharmasys"."user_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_location_status_enum" RENAME TO "stock_location_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_location_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" TYPE "pharmasys"."stock_location_status_enum" USING "status"::"text"::"pharmasys"."stock_location_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_location_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_reason_status_enum" RENAME TO "transfer_reason_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_reason_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" TYPE "pharmasys"."transfer_reason_status_enum" USING "status"::"text"::"pharmasys"."transfer_reason_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_reason_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_status_enum" RENAME TO "transfer_request_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" TYPE "pharmasys"."transfer_request_status_enum" USING "status"::"text"::"pharmasys"."transfer_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."type_status_enum" RENAME TO "type_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."type_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" TYPE "pharmasys"."type_status_enum" USING "status"::"text"::"pharmasys"."type_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."type_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."presentation_status_enum" RENAME TO "presentation_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."presentation_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" TYPE "pharmasys"."presentation_status_enum" USING "status"::"text"::"pharmasys"."presentation_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."presentation_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."dosage_status_enum" RENAME TO "dosage_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."dosage_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" TYPE "pharmasys"."dosage_status_enum" USING "status"::"text"::"pharmasys"."dosage_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."dosage_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."subtype_status_enum" RENAME TO "subtype_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."subtype_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" TYPE "pharmasys"."subtype_status_enum" USING "status"::"text"::"pharmasys"."subtype_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."subtype_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_status_enum" RENAME TO "item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" TYPE "pharmasys"."item_status_enum" USING "status"::"text"::"pharmasys"."item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_item_status_enum" RENAME TO "transfer_request_item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" TYPE "pharmasys"."transfer_request_item_status_enum" USING "status"::"text"::"pharmasys"."transfer_request_item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_item_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_item_transfer_status_enum" RENAME TO "transfer_request_item_transfer_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_item_transfer_status_enum" AS ENUM('A', 'S', 'F', 'C')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" TYPE "pharmasys"."transfer_request_item_transfer_status_enum" USING "transfer_status"::"text"::"pharmasys"."transfer_request_item_transfer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_item_transfer_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_transfer_status_enum" RENAME TO "stock_transfer_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_transfer_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" TYPE "pharmasys"."stock_transfer_status_enum" USING "status"::"text"::"pharmasys"."stock_transfer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_transfer_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."company_type_status_enum" RENAME TO "company_type_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."company_type_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" TYPE "pharmasys"."company_type_status_enum" USING "status"::"text"::"pharmasys"."company_type_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."company_type_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."company_status_enum" RENAME TO "company_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."company_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" TYPE "pharmasys"."company_status_enum" USING "status"::"text"::"pharmasys"."company_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."company_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."batch_status_enum" RENAME TO "batch_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."batch_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" TYPE "pharmasys"."batch_status_enum" USING "status"::"text"::"pharmasys"."batch_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."batch_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_transfer_item_status_enum" RENAME TO "stock_transfer_item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_transfer_item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" TYPE "pharmasys"."stock_transfer_item_status_enum" USING "status"::"text"::"pharmasys"."stock_transfer_item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_transfer_item_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_balance_status_enum" RENAME TO "stock_balance_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_balance_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" TYPE "pharmasys"."stock_balance_status_enum" USING "status"::"text"::"pharmasys"."stock_balance_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_balance_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."advice_status_enum" RENAME TO "advice_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."advice_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" TYPE "pharmasys"."advice_status_enum" USING "status"::"text"::"pharmasys"."advice_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."advice_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."prescriptor_status_enum" RENAME TO "prescriptor_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."prescriptor_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" TYPE "pharmasys"."prescriptor_status_enum" USING "status"::"text"::"pharmasys"."prescriptor_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."prescriptor_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."patient_status_enum" RENAME TO "patient_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."patient_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" TYPE "pharmasys"."patient_status_enum" USING "status"::"text"::"pharmasys"."patient_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."patient_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_dispensation_status_enum" RENAME TO "item_dispensation_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_dispensation_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" TYPE "pharmasys"."item_dispensation_status_enum" USING "status"::"text"::"pharmasys"."item_dispensation_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_dispensation_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_dispensation_item_status_enum" RENAME TO "item_dispensation_item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_dispensation_item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" TYPE "pharmasys"."item_dispensation_item_status_enum" USING "status"::"text"::"pharmasys"."item_dispensation_item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_dispensation_item_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."exit_item_type_status_enum" RENAME TO "exit_item_type_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."exit_item_type_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" TYPE "pharmasys"."exit_item_type_status_enum" USING "status"::"text"::"pharmasys"."exit_item_type_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."exit_item_type_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_exit_status_enum" RENAME TO "inventory_exit_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_exit_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" TYPE "pharmasys"."inventory_exit_status_enum" USING "status"::"text"::"pharmasys"."inventory_exit_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_exit_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory-exit-item_status_enum" RENAME TO "inventory-exit-item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory-exit-item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" TYPE "pharmasys"."inventory-exit-item_status_enum" USING "status"::"text"::"pharmasys"."inventory-exit-item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory-exit-item_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."entry_item_type_status_enum" RENAME TO "entry_item_type_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."entry_item_type_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" TYPE "pharmasys"."entry_item_type_status_enum" USING "status"::"text"::"pharmasys"."entry_item_type_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."entry_item_type_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_entry_status_enum" RENAME TO "inventory_entry_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_entry_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" TYPE "pharmasys"."inventory_entry_status_enum" USING "status"::"text"::"pharmasys"."inventory_entry_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_entry_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_entry_item_status_enum" RENAME TO "inventory_entry_item_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_entry_item_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" TYPE "pharmasys"."inventory_entry_item_status_enum" USING "status"::"text"::"pharmasys"."inventory_entry_item_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" SET DEFAULT 'ATIVO'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_entry_item_status_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_entry_item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" TYPE "pharmasys"."inventory_entry_item_status_enum_old" USING "status"::"text"::"pharmasys"."inventory_entry_item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry_item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_entry_item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_entry_item_status_enum_old" RENAME TO "inventory_entry_item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_entry_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" TYPE "pharmasys"."inventory_entry_status_enum_old" USING "status"::"text"::"pharmasys"."inventory_entry_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_entry" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_entry_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_entry_status_enum_old" RENAME TO "inventory_entry_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."entry_item_type_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" TYPE "pharmasys"."entry_item_type_status_enum_old" USING "status"::"text"::"pharmasys"."entry_item_type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."entry_item_type" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."entry_item_type_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."entry_item_type_status_enum_old" RENAME TO "entry_item_type_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory-exit-item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" TYPE "pharmasys"."inventory-exit-item_status_enum_old" USING "status"::"text"::"pharmasys"."inventory-exit-item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory-exit-item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory-exit-item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory-exit-item_status_enum_old" RENAME TO "inventory-exit-item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."inventory_exit_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" TYPE "pharmasys"."inventory_exit_status_enum_old" USING "status"::"text"::"pharmasys"."inventory_exit_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."inventory_exit" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."inventory_exit_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."inventory_exit_status_enum_old" RENAME TO "inventory_exit_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."exit_item_type_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" TYPE "pharmasys"."exit_item_type_status_enum_old" USING "status"::"text"::"pharmasys"."exit_item_type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."exit_item_type" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."exit_item_type_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."exit_item_type_status_enum_old" RENAME TO "exit_item_type_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_dispensation_item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" TYPE "pharmasys"."item_dispensation_item_status_enum_old" USING "status"::"text"::"pharmasys"."item_dispensation_item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation_item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_dispensation_item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_dispensation_item_status_enum_old" RENAME TO "item_dispensation_item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_dispensation_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" TYPE "pharmasys"."item_dispensation_status_enum_old" USING "status"::"text"::"pharmasys"."item_dispensation_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item_dispensation" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_dispensation_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_dispensation_status_enum_old" RENAME TO "item_dispensation_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."patient_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" TYPE "pharmasys"."patient_status_enum_old" USING "status"::"text"::"pharmasys"."patient_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."patient" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."patient_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."patient_status_enum_old" RENAME TO "patient_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."prescriptor_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" TYPE "pharmasys"."prescriptor_status_enum_old" USING "status"::"text"::"pharmasys"."prescriptor_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."prescriptor" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."prescriptor_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."prescriptor_status_enum_old" RENAME TO "prescriptor_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."advice_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" TYPE "pharmasys"."advice_status_enum_old" USING "status"::"text"::"pharmasys"."advice_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."advice" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."advice_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."advice_status_enum_old" RENAME TO "advice_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_balance_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" TYPE "pharmasys"."stock_balance_status_enum_old" USING "status"::"text"::"pharmasys"."stock_balance_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_balance" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_balance_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_balance_status_enum_old" RENAME TO "stock_balance_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_transfer_item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" TYPE "pharmasys"."stock_transfer_item_status_enum_old" USING "status"::"text"::"pharmasys"."stock_transfer_item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer_item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_transfer_item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_transfer_item_status_enum_old" RENAME TO "stock_transfer_item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."batch_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" TYPE "pharmasys"."batch_status_enum_old" USING "status"::"text"::"pharmasys"."batch_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."batch" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."batch_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."batch_status_enum_old" RENAME TO "batch_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."company_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" TYPE "pharmasys"."company_status_enum_old" USING "status"::"text"::"pharmasys"."company_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."company_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."company_status_enum_old" RENAME TO "company_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."company_type_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" TYPE "pharmasys"."company_type_status_enum_old" USING "status"::"text"::"pharmasys"."company_type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."company_type" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."company_type_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."company_type_status_enum_old" RENAME TO "company_type_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_transfer_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" TYPE "pharmasys"."stock_transfer_status_enum_old" USING "status"::"text"::"pharmasys"."stock_transfer_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_transfer" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_transfer_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_transfer_status_enum_old" RENAME TO "stock_transfer_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_item_transfer_status_enum_old" AS ENUM('O', 'S', 'F', 'C')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" TYPE "pharmasys"."transfer_request_item_transfer_status_enum_old" USING "transfer_status"::"text"::"pharmasys"."transfer_request_item_transfer_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "transfer_status" SET DEFAULT 'O'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_item_transfer_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_item_transfer_status_enum_old" RENAME TO "transfer_request_item_transfer_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" TYPE "pharmasys"."transfer_request_item_status_enum_old" USING "status"::"text"::"pharmasys"."transfer_request_item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request_item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_item_status_enum_old" RENAME TO "transfer_request_item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."item_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" TYPE "pharmasys"."item_status_enum_old" USING "status"::"text"::"pharmasys"."item_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."item" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."item_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."item_status_enum_old" RENAME TO "item_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."subtype_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" TYPE "pharmasys"."subtype_status_enum_old" USING "status"::"text"::"pharmasys"."subtype_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."subtype" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."subtype_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."subtype_status_enum_old" RENAME TO "subtype_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."dosage_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" TYPE "pharmasys"."dosage_status_enum_old" USING "status"::"text"::"pharmasys"."dosage_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."dosage" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."dosage_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."dosage_status_enum_old" RENAME TO "dosage_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."presentation_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" TYPE "pharmasys"."presentation_status_enum_old" USING "status"::"text"::"pharmasys"."presentation_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."presentation" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."presentation_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."presentation_status_enum_old" RENAME TO "presentation_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."type_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" TYPE "pharmasys"."type_status_enum_old" USING "status"::"text"::"pharmasys"."type_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."type" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."type_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."type_status_enum_old" RENAME TO "type_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_request_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" TYPE "pharmasys"."transfer_request_status_enum_old" USING "status"::"text"::"pharmasys"."transfer_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_request" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_request_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_request_status_enum_old" RENAME TO "transfer_request_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."transfer_reason_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" TYPE "pharmasys"."transfer_reason_status_enum_old" USING "status"::"text"::"pharmasys"."transfer_reason_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."transfer_reason" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."transfer_reason_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."transfer_reason_status_enum_old" RENAME TO "transfer_reason_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."stock_location_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" TYPE "pharmasys"."stock_location_status_enum_old" USING "status"::"text"::"pharmasys"."stock_location_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."stock_location" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."stock_location_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."stock_location_status_enum_old" RENAME TO "stock_location_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."user_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" TYPE "pharmasys"."user_status_enum_old" USING "status"::"text"::"pharmasys"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."user" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."user_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."user_status_enum_old" RENAME TO "user_status_enum"`);
        await queryRunner.query(`CREATE TYPE "pharmasys"."role_status_enum_old" AS ENUM('A', 'I')`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" TYPE "pharmasys"."role_status_enum_old" USING "status"::"text"::"pharmasys"."role_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pharmasys"."role" ALTER COLUMN "status" SET DEFAULT 'A'`);
        await queryRunner.query(`DROP TYPE "pharmasys"."role_status_enum"`);
        await queryRunner.query(`ALTER TYPE "pharmasys"."role_status_enum_old" RENAME TO "role_status_enum"`);
    }

}
