export enum AdviceEnum {
  CRM = 'CRM',
  CRO = 'CRO',
  COREM = 'COREM',
  CRMV = 'CRMV',
  CRF = 'CRF',
  CRN = 'CRN',
  CONSELHO_REGIONAL_MEDICINA = 'CONSELHO_REGIONAL_MEDICINA',
  CONSELHO_REGIONAL_ODONTOLOGIA = 'CONSELHO_REGIONAL_ODONTOLOGIA',
  CONSELHO_REGIONAL_TECNICOS_RADIOLOGIA = 'CONSELHO_REGIONAL_TECNICOS_RADIOLOGIA',
  CONSELHO_REGIONAL_MEDICINA_VETERINARIA = 'CONSELHO_REGIONAL_MEDICINA_VETERINARIA',
  CONSELHO_REGIONAL_FARMACIA = 'CONSELHO_REGIONAL_FARMACIA',
  CONSELHO_REGIONAL_NUTRICAO = 'CONSELHO_REGIONAL_NUTRICAO',
}

export enum AdviceEnumTranslated {
  CRM = 'CRM',
  CRO = 'CRO',
  COREM = 'COREM',
  CRMV = 'CRMV',
  CRF = 'CRF',
  CRN = 'CRN',
  CONSELHO_REGIONAL_MEDICINA = 'Conselho Regional de Medicina',
  CONSELHO_REGIONAL_ODONTOLOGIA = 'Conselho Regional de Odontologia',
  CONSELHO_REGIONAL_TECNICOS_RADIOLOGIA = 'Conselho Regional de Técnicos em Radiologia',
  CONSELHO_REGIONAL_MEDICINA_VETERINARIA = 'Conselho Regional de Medicina Veterinária',
  CONSELHO_REGIONAL_FARMACIA = 'Conselho Regional de Farmácia',
  CONSELHO_REGIONAL_NUTRICAO = 'Conselho Regional de Nutrição',
}
